const SET_ALERT = 'SET_ALERT';
const REMOVE_ALERT = 'REMOVE_ALERT';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const USER_LOADED = 'USER_LOADED';
const AUTH_ERROR = 'AUTH_ERROR';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGIN_OUT = 'LOGIN_OUT';
const GET_PROFILE = 'GET_PROFILE';
const GET_PROFILES = 'GET_PROFILES';
const GET_REPOS = 'GET_REPOS';
const UPDATE_PROFILE = 'UPDATE_PROFILE';
const CLEAR_PROFILE = 'CLEAR_PROFILE';
const PROFILE_ERROR = 'PROFILE_ERROR';
const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
const GET_POSTS = 'GET_POSTS';
const POST_ERROR = 'POST_ERROR';
const UPDATE_LIKES = 'UPDATE_LIKES';

export {
  SET_ALERT, 
  REMOVE_ALERT,
  REGISTER_SUCCESS,
  REGISTER_FAIL,
  USER_LOADED,
  AUTH_ERROR,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOGIN_OUT,
  GET_PROFILE,
  GET_PROFILES,
  GET_REPOS,
  UPDATE_PROFILE,
  CLEAR_PROFILE,
  PROFILE_ERROR,
  ACCOUNT_DELETED,
  GET_POSTS,
  POST_ERROR,
  UPDATE_LIKES
};



